# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Util
version:      0.03
version_from: lib/Tie/Util.pm
installdirs:  site
requires:
    B:                             0
    constant:                      0
    Exporter:                      5.57
    overload:                      0
    Scalar::Util:                  1.09
    Symbol:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
